language: python
dist: xenial
matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON_VER=3.6 LINT=false
  - os: osx
    language: generic
    env: PYTHON_VER=3.7 LINT=false
  - os: linux
    python: 3.6
    env: PYTHON_VER=3.6 LINT=false
  - os: linux
    python: 3.7
    env: PYTHON_VER=3.7 LINT=false
  # Add checks to ensure the repo has been linted /
  # formatted with black / flake8 / isort
  - os: linux
    env: PYTHON_VER=3.6 LINT=true
env:
  global:
  - OE_LICENSE="$HOME/oe_license.txt"
before_install:
- openssl aes-256-cbc -K $encrypted_78085d00ae9a_key -iv $encrypted_78085d00ae9a_iv
  -in oe_license.txt.enc -out $OE_LICENSE -d
- uname -a
- df -h
- ulimit -a
- source devtools/travis-ci/before_install.sh
- python -V
install:
- python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/test_env.yaml
- conda activate test
- python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
- python setup.py develop --no-deps
script:
  - if [[ $LINT == false ]]; then pytest -v --cov=propertyestimator propertyestimator/tests/ ; fi
  - if [[ $LINT == true ]]; then conda install flake8 ; flake8 propertyestimator ; flake8 examples ; fi
  - if [[ $LINT == true ]]; then conda install flake8-black; black propertyestimator --check; black examples --check ; fi
notifications:
  email: false
after_success:
  - if [[ $LINT == false ]]; codecov ; fi
