name: propertyestimator
channels:
    - conda-forge
    - omnia
dependencies:
    # Base depends
    - python ==3.6
    - setuptools

    # Sphinx specific
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1
    - sphinx_rtd_theme

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - openmm
    - pint >=0.10.1
    - packmol
    - pymbar >=3.0.5
    - dask >=2.7.0
    - distributed >=2.7.0
    - dask-jobqueue >=0.7.0
    - uncertainties
