name: propertyestimator
channels:
    - omnia
    - conda-forge
dependencies:
    # Base depends
    - python ==3.6
    - setuptools

    # Sphinx specific
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1
    - sphinx_rtd_theme

    # Standard dependencies
    - numpy
    - pandas
    - lxml
    - icu 58*  # REQUIRED - DO NOT REMOVE.
    - openmm
    - packmol
    - pymbar
    - dask
    - dask_jobqueue
    - tornado <6
    - uncertainties
